variables:
  docker_image_name: "$CI_REGISTRY/cour-de-cassation/juridependencies/fake-data:$CI_COMMIT_SHORT_SHA"

stages:
  - build
  - deploy

build_docker_image:
  stage: build
  image: docker:29.0.4-dind
  variables:
    HTTP_PROXY: $HTTP_PROXY_DEV
    HTTPS_PROXY: $HTTPS_PROXY_DEV
  script: 
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Building Juridependencies image"
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        -t $docker_image_name -f fake-data/Dockerfile .
    - docker push $docker_image_name
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "local" || $CI_COMMIT_BRANCH == "feature/deploy-fake-data-seeder"'
  tags:
    - docker

deploy_dev:
  stage: deploy
  image: alpine/ansible:2.16.1
  variables:
    DOLLAR: $$
  script:
    - mkdir /root/.ssh
    - cat $SSH_KEY > /root/.ssh/id_rsa
    - cat $KNOWN_HOSTS > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/known_hosts
    - ansible-playbook -e docker_image_name=$docker_image_name
      -i ansible/inventory/dev.yml ansible/deploy-pod.yml
      --vault-password-file=$ANSIBLE_VAULT_PASS
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "local" || $CI_COMMIT_BRANCH == "feature/deploy-fake-data-seeder"'
  tags:
    - docker
  dependencies:
    - build_docker_image