ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER ${DBDSI_USER_JURINET} IDENTIFIED BY ${DBDSI_PASS_JURINET} QUOTA UNLIMITED ON USERS;

GRANT ALL PRIVILEGES TO ${DBDSI_USER_JURINET};

CREATE USER ${DBDSI_USER_JURICA} IDENTIFIED BY ${DBDSI_PASS_JURICA} QUOTA UNLIMITED ON USERS;

GRANT ALL PRIVILEGES TO ${DBDSI_USER_JURICA};

CREATE USER ${DBDSI_USER_PENAL} IDENTIFIED BY ${DBDSI_PASS_PENAL} QUOTA UNLIMITED ON USERS;

GRANT ALL PRIVILEGES TO ${DBDSI_USER_PENAL};

CREATE USER ${DBDSI_USER_GRCOM} IDENTIFIED BY ${DBDSI_PASS_GRCOM} QUOTA UNLIMITED ON USERS;

GRANT ALL PRIVILEGES TO ${DBDSI_USER_GRCOM};