---
- name: Creation Secret
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ namespace }}-secret"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ namespace }}"
      type: Opaque
      data:
        HTTP_PROXY: "{{ HTTP_PROXY | b64encode }}"
        HTTPS_PROXY: "{{ HTTPS_PROXY | b64encode }}"
        DBSDER_HOST: "{{ DBSDER_HOST | b64encode }}"
        DBSDER_PORT: "{{ DBSDER_PORT | b64encode }}"
        DBSDER_DATABASE: "{{ DBSDER_DATABASE | b64encode }}"
        INDEX_DATABASE: "{{ INDEX_DATABASE | b64encode }}"
        DBDSI_HOST: "{{ DBDSI_HOST | b64encode }}"
        DBDSI_USER_JURICA: "{{ DBDSI_USER_JURICA | b64encode }}"
        DBDSI_PASS_JURICA: "{{ DBDSI_PASS_JURICA | b64encode }}"
        DBDSI_USER_JURINET: "{{ DBDSI_USER_JURINET | b64encode }}"
        DBDSI_PASS_JURINET: "{{ DBDSI_PASS_JURINET | b64encode }}"
        DBDSI_USER_PENAL: "{{ DBDSI_USER_PENAL | b64encode }}"
        DBDSI_PASS_PENAL: "{{ DBDSI_PASS_PENAL | b64encode }}"
        DBDSI_USER_GRCOM: "{{ DBDSI_USER_GRCOM | b64encode }}"
        DBDSI_PASS_GRCOM: "{{ DBDSI_PASS_GRCOM | b64encode }}"
        DB_TABLE: "{{ DB_TABLE | b64encode }}"
        DB_TABLE_JURICA: "{{ DB_TABLE_JURICA | b64encode }}"
        LABELDB_HOST: "{{ LABELDB_HOST | b64encode }}"
        LABELDB_PORT: "{{ LABELDB_PORT | b64encode }}"
        LABELDB_DATABASE: "{{ LABELDB_DATABASE | b64encode }}"
        BUCKET_HOST: "{{ BUCKET_HOST | b64encode }}"
        BUCKET_PORT: "{{ BUCKET_PORT | b64encode }}"
        BUCKET_JURITJ_NAME_RAW: "{{ BUCKET_JURITJ_NAME_RAW | b64encode }}"
        BUCKET_JURITCOM_NAME_NORMALIZED: "{{ BUCKET_JURITCOM_NAME_NORMALIZED | b64encode }}"
        BUCKET_JURITCOM_NAME_RAW: "{{ BUCKET_JURITCOM_NAME_RAW | b64encode }}"
        BUCKET_JURITCOM_NAME_PDF2TEXT_SUCCESS: "{{ BUCKET_JURITCOM_NAME_PDF2TEXT_SUCCESS | b64encode }}"
        BUCKET_JURITCOM_NAME_PDF2TEXT_FAILED: "{{ BUCKET_JURITCOM_NAME_PDF2TEXT_FAILED | b64encode }}"
        BUCKET_JURITCOM_NAME_DELETION: "{{ BUCKET_JURITCOM_NAME_DELETION | b64encode }}"
        BUCKET_JURITCOM_NAME_PDF: "{{ BUCKET_JURITCOM_NAME_PDF | b64encode }}"
        BUCKET_PORTALIS_COLLECT_NAME: "{{ BUCKET_PORTALIS_COLLECT_NAME | b64encode }}"
        BUCKET_ACCESS_KEY: "{{ BUCKET_ACCESS_KEY | b64encode }}"
        BUCKET_ACCESS_SECRET: "{{ BUCKET_ACCESS_SECRET | b64encode }}"

