---
- name: Creation Secret
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ namespace }}-secret"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ namespace }}"
      type: Opaque
      data:
        HTTP_PROXY: "{{ HTTP_PROXY | b64encode }}"
        HTTPS_PROXY: "{{ HTTPS_PROXY | b64encode }}"
        MODEL_PATH: "{{ MODEL_PATH | b64encode }}"
        MONGO_DEV_CONNECTION_STRING: "{{ MONGO_DEV_CONNECTION_STRING | b64encode }}"
        MONGO_PREPROD_RAWFILES: "{{ MONGO_PREPROD_RAWFILES | b64encode}}"
        MONGO_PROD_RAWFILES: "{{ MONGO_PROD_RAWFILES | b64encode }}"
        S3_URL: "{{ S3_URL | b64encode }}"
        S3_REGION: "{{ S3_REGION | b64encode }}"
        S3_ACCESS_KEY: "{{ S3_ACCESS_KEY | b64encode }}"
        S3_SECRET_KEY: "{{ S3_SECRET_KEY | b64encode }}"
        S3_BUCKET_NAME_NORMALIZED_TJ: "{{ S3_BUCKET_NAME_NORMALIZED_TJ | b64encode }}"
        S3_BUCKET_NAME_RAW_TJ: "{{ S3_BUCKET_NAME_RAW_TJ | b64encode }}"
        S3_BUCKET_NAME_NORMALIZED_TCOM: "{{ S3_BUCKET_NAME_NORMALIZED_TCOM | b64encode }}"
        DBDSI_HOST_JURINET: "{{ DBDSI_HOST_JURINET | b64encode }}"
        DBDSI_HOST_JURICA: "{{ DBDSI_HOST_JURICA | b64encode }}"
        DBDSI_USER_JURICA: "{{ DBDSI_USER_JURICA | b64encode }}"
        DBDSI_PASS_JURICA: "{{ DBDSI_PASS_JURICA | b64encode }}"
        DBDSI_TABLE_JURICA: "{{ DBDSI_TABLE_JURICA | b64encode }}"
        DBDSI_USER_JURINET: "{{ DBDSI_USER_JURINET | b64encode }}"
        DBDSI_PASS_JURINET: "{{ DBDSI_PASS_JURINET | b64encode }}"
        DBDSI_TABLE_JURINET: "{{ DBDSI_TABLE_JURINET | b64encode }}"
        ENV: "{{ ENV | b64encode }}"
        S3_BUCKET_NAME_CPH: "{{ S3_BUCKET_NAME_CPH | b64encode }}"

