HTTP_PROXY: "{{ vault_http_proxy }}"
HTTPS_PROXY: "{{ vault_https_proxy }}"

NODE_ENV: "DEV"

DBSDER_HOST: "{{ VAULT_DBSDER_HOST }}"
DBSDER_NAME: "{{ VAULT_DBSDER_NAME }}"
DBSDER_PORT: "{{ VAULT_DBSDER_PORT }}"
DBSDER_DATABASE: "{{ VAULT_DBSDER_DATABASE }}"
INDEX_DATABASE: "{{ VAULT_INDEX_DATABASE }}"

DBDSI_NAME: "{{ VAULT_DBDSI_NAME }}"
DBDSI_HOST: "{{ VAULT_DBDSI_HOST }}"
DBDSI_EXTERNAL_PORT: "{{ VAULT_DBDSI_EXTERNAL_PORT }}"
DBDSI_ADMIN_PASS: "{{ VAULT_DBDSI_ADMIN_PASS }}"
DBDSI_USER_JURICA: "{{ VAULT_DBDSI_USER_JURICA }}"
DBDSI_PASS_JURICA: "{{ VAULT_DBDSI_PASS_JURICA }}"
DBDSI_USER_JURINET: "{{ VAULT_DBDSI_USER_JURINET }}"
DBDSI_PASS_JURINET: "{{ VAULT_DBDSI_PASS_JURINET }}"
DBDSI_USER_PENAL: "{{ VAULT_DBDSI_USER_PENAL }}"
DBDSI_PASS_PENAL: "{{ VAULT_DBDSI_PASS_PENAL }}"
DBDSI_USER_GRCOM: "{{ VAULT_DBDSI_USER_GRCOM }}"
DBDSI_PASS_GRCOM: "{{ VAULT_DBDSI_PASS_GRCOM }}"
DB_TABLE: "{{ VAULT_DB_TABLE }}"
DB_TABLE_JURICA: "{{ VAULT_DB_TABLE_JURICA }}"

LABELDB_HOST: "{{ VAULT_LABELDB_HOST }}"
LABELDB_NAME: "{{ VAULT_LABELDB_NAME }}"
LABELDB_PORT: "{{ VAULT_LABELDB_PORT }}"
LABELDB_DATABASE: "{{ VAULT_LABELDB_DATABASE }}"

BUCKET_HOST: "{{ VAULT_BUCKET_HOST }}"
BUCKET_NAME: "{{ VAULT_BUCKET_NAME }}"
BUCKET_CONSOLE_PORT: "{{ VAULT_BUCKET_CONSOLE_PORT }}"
BUCKET_PORT: "{{ VAULT_BUCKET_PORT }}"
BUCKET_USER: "{{ VAULT_BUCKET_USER }}"
BUCKET_PASS: "{{ VAULT_BUCKET_PASS }}"
BUCKET_JURITJ_NAME_RAW: "{{ VAULT_BUCKET_JURITJ_NAME_RAW }}"
BUCKET_JURITCOM_NAME_NORMALIZED: "{{ VAULT_BUCKET_JURITCOM_NAME_NORMALIZED }}"
BUCKET_JURITCOM_NAME_RAW: "{{ VAULT_BUCKET_JURITCOM_NAME_RAW }}"
BUCKET_JURITCOM_NAME_PDF2TEXT_SUCCESS: "{{ VAULT_BUCKET_JURITCOM_NAME_PDF2TEXT_SUCCESS }}"
BUCKET_JURITCOM_NAME_PDF2TEXT_FAILED: "{{ VAULT_BUCKET_JURITCOM_NAME_PDF2TEXT_FAILED }}"
BUCKET_JURITCOM_NAME_DELETION: "{{ VAULT_BUCKET_JURITCOM_NAME_DELETION }}"
BUCKET_JURITCOM_NAME_PDF: "{{ VAULT_BUCKET_JURITCOM_NAME_PDF }}"
BUCKET_PORTALIS_COLLECT_NAME: "{{ VAULT_BUCKET_PORTALIS_COLLECT_NAME }}"
BUCKET_ACCESS_KEY: "{{ VAULT_BUCKET_ACCESS_KEY }}"
